carrot_count = 0
whip_count = 0
def display_status():
        print("\n==== 현재 상태 ====")
            print("당근 개수 :", carrot_count)
                print("채찍 개수 :", whip_count)
                    print("==================\n")
                    def add_carrots():
                        global carrot_count 
                            try:
                                            num = int(input("추가할 당근의 수를 입력하세요: "))
                                                    if num < 0:
                                                                print("음수는 입력할 수 없습니다!")
                                                                        else:
                                                                                    carrot_count += num
                                                                                                print(f"{num}개의 당근이 추가되었습니다.")
                                                                                                    except ValueError:
                                                                                                            print("유효한 정수를 입력하세요!")
                                                                                                            def add_whips():
                                                                                                                global whip_count 
                                                                                                                    try:
                                                                                                                                    num = int(input("추가할 채찍의 수를 입력하세요: "))
                                                                                                                                            if num < 0:
                                                                                                                                                        print("음수는 입력할 수 없습니다!")
                                                                                                                                                                else:
                                                                                                                                                                            whip_count += num
                                                                                                                                                                                        print(f"{num}개의 채찍이 추가되었습니다.")
                                                                                                                                                                                            except ValueError:
                                                                                                                                                                                                    print("유효한 정수를 입력하세요!")
                                                                                                                                                                                                    def use_whip():
                                                                                                                                                                                                        global carrot_count, whip_count  
                                                                                                                                                                                                                if whip_count <= 0:
                                                                                                                                                                                                                        print("사용 가능한 채찍이 없습니다!")
                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                        if carrot_count < 10:
                                                                                                                                                                                                                                                print("당근이 부족합니다! 최소 10개의 당근이 필요합니다.")
                                                                                                                                                                                                                                                        return
                                                                                                                                                                                                                                                                whip_count -= 1
                                                                                                                                                                                                                                                                    carrot_count -= 10
                                                                                                                                                                                                                                                                        print("채찍 1개 사용! 당근 10개가 제거되었습니다.")
                                                                                                                                                                                                                                                                        def main():
                                                                                                                                                                                                                                                                            while True
                                                                                                                                                                                                                                                                                            display_status()
                                                                                                                                                                                                                                                                                                            print("메뉴를 선택하세요:")
                                                                                                                                                                                                                                                                                                                    print("1: 당근 추가하기")
                                                                                                                                                                                                                                                                                                                            print("2: 채찍 추가하기")
                                                                                                                                                                                                                                                                                                                                    print("3: 채찍 사용하기 (당근 10개 제거)")
                                                                                                                                                                                                                                                                                                                                            print("4: 프로그램 종료")
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            choice = input("옵션 번호를 입력하세요: ")
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            if choice == "1":
                                                                                                                                                                                                                                                                                                                                                                                        add_carrots()
                                                                                                                                                                                                                                                                                                                                                                                                elif choice == "2":
                                                                                                                                                                                                                                                                                                                                                                                                            add_whips()
                                                                                                                                                                                                                                                                                                                                                                                                                    elif choice == "3":
                                                                                                                                                                                                                                                                                                                                                                                                                                use_whip()
                                                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == "4":
                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("프로그램을 종료합니다!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("잘못된 입력입니다. 다시 시도하세요.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        